### ISSUE TITLE
Doesn't detect changes for functions that generate DOM component changes

### ISSUE THREAD

**Issue by rob2d** [milankinen/livereactload#154]
I have a component which has a class. I have noticed that reloading does not work if a function contained in a component has code which is changed. Example:

```
class MainApp extends Component
{
    constructor(props)
    {
        super(props);

        this.DOM =
        {
            G :     // generator functions
            {
                contactButton : (p)=>
                {
                    return (
                        <Button className={this.classes.contactButtonContainer}
                            style={
                            {
                                display : 'inline-flex',
                                justifyContent : 'center',
                                flexDirection  : 'column'
                            }}
                            onClick={()=> {location.href = p.url}}>
                            <i className={`${p.className}`}/>
                        </Button>
                    );
                }
            }
        };
    }
    static contextTypes = { store : PropTypes.object.isRequired };
    render ()
    {
        const { location } = this.props;
        return (
            <MuiThemeProvider muiTheme={getMuiTheme(baseTheme)}>
                <div className="appWrapper">
                    <div className="mainContent">
                        <AppHeader/>
                        {(()=> { switch(location.pathname)
                        {
                            case '/':
                            case '/projects':
                                return (<ProjectsPanel className='mainContent'/>);
                            case '/projects/:project_id':
                                return (<Project className='mainContent'/>);
                            case '/cv':
                                return (<CV className='mainContent'/>);
                        }})()}
                        </div>
                    <div className="appFooter">
                        {this.DOM.G.contactButton(
                        {
                            className : 'mdi mdi-github-box',
                            url       : 'http://somewhere'
                        })}
                        {this.DOM.G.contactButton(
                            {
                                className : 'rc3 rc3-npm-box',
                                url       : 'http://somewhere'
                            })}
                        {this.DOM.G.contactButton(
                            {
                                className : 'mdi mdi-code-tags',
                                url              : 'http://somewhere''
                            })}
                    </div>
                </div>
            </MuiThemeProvider>
```

If I edit the definition of `this.DOM.G.contactButton`, no changes are detected when reloading.

**Comment by EugeneZ** [comment]
This is fixed in `livereactload@next`. Another `next` to add to your list. 😄 

See upgrade instructions [here](https://github.com/milankinen/livereactload/tree/4.x#migration-from-livereactload-3x).

**Comment by rob2d** [comment]
Amazing! Thanks for the quick reply :) Checking that out and will close right after.

**Comment by rob2d** [comment]
Tried to follow the guide. Unfortunately, I am experiencing the following when trying to run my gulp setup now:

```Unknown plugin "react-hot-loader/babel" specified in "base" at 3, attempted to resolve relative to "..."```

[double checked and upgraded all babel related dependencies to the latest :/]

**Comment by rob2d** [comment]
So I found the issue with that -- Just needed `react-hot-loader@next`! 
Getting a familiar feeling here... 🤣  

Another thing now, it is still not refreshing/updating in the example case I provided, but I am also getting an invariant violation for including `inject-tap-event-plugin` more than once which was included as it continues to load the client app over and over again. I will try to alleviate that issue to see if it's what is causing it or whether it's `livereactload` at this point.

**Comment by EugeneZ** [comment]
By default, the new `livereactload` assumes your code is idempotent (can be run over and over without issue) and the `inject-tap-event-plugin`  is not idempotent. Wrap it in a try catch block.

**Comment by rob2d** [comment]
thanks for the elegant solution. I've actually got another workaround for that -- simply import `inject-tap-event-plugin` and then call it in an outside module, then require it in your client app.

e.g.

```
import injectTapEventPlugin from 'react-tap-event-plugin';

// for onClick/onTouchTap events with MUI & React
injectTapEventPlugin();
```

and in your client app : `import injectTapEventPlugin from './wherever/injectTapEventPlugin'`

... unfortunately, after that... the issue described remains on the `@next` branch so far 😅...

**Comment by rob2d** [comment]
To update: there are no more issues that might be conflicting with the build, but the issue posted above still seems to be there unfortunately 😐

**Comment by milankinen** [comment]
>To update: there are no more issues that might be conflicting with the build, but the issue posted above still seems to be there unfortunately

Do you mean the reload problem or `inject-tap-event-plugin` error?

**Comment by rob2d** [comment]
Sorry for the ambiguity there -- the reload issue described/#154.

**Comment by milankinen** [comment]
I think the cause of this issue is that the factory function (`DOM.G.contactButton`) is bound in the component's constructor and the returned value is not a component. Hence `react-hot-loader` can't intercept the function call and proxy the return value correctly.

How about if you extracted the contact button to its own separate functional component? Would that work as expected? 

```js
class MainApp extends Component
{
    constructor(props)
    {
        super(props);

        this.DOM =
        {
            G :     // generator functions
            {
                contactButton : (p) => 
                  <ContactButton {...p} btnClass={this.classes.contactButtonContainer} />
            }
        };
    }
    render ()
    {
        return (
                <div className="appWrapper">
                    <div className="mainContent">
                        <AppHeader/>
                        <div>- insert body content here -</div>
                    </div>
                    <div className="appFooter">
                        {this.DOM.G.contactButton(
                        {
                            className : 'mdi mdi-github-box',
                            url       : 'http://somewhere'
                        })}
                        {this.DOM.G.contactButton(
                            {
                                className : 'rc3 rc3-npm-box',
                                url       : 'http://somewhere'
                            })}
                        {this.DOM.G.contactButton(
                            {
                                className : 'mdi mdi-code-tags',
                                url              : 'http://somewhere'
                            })}
                    </div>
                </div>
                );
        }
}

function ContactButton({url, className, btnClass}) {
  return (
    <Button className={btnClass}
       onClick={()=> {location.href = url}}>
       <i className={className}/>
    </Button>
  );
}
```

**Comment by rob2d** [comment]
Thanks for the thoughtful reply. I have actually resorted do doing just that. One reason why I had done things this way is `material-ui` now uses JSS and has to be compiled with a context value binded to the style for classNames (I mean, it doesn't *have to*, but for the sake of consistency). I also wasn't sure if the technology within JSS that re-writes CSS to the DOM would have slowdown with more sheets to do that.

But I guess a little more boiler-plate here and there won't be the end of the world. Thanks 😄 👍

**Comment by EugeneZ** [comment]
Apologies for the delay and for suggesting that the new beta would fix the issue. I got it confused with a different fix.

However, I recreated your code with `react-hot-boilerplate` [here](https://github.com/EugeneZ/react-hot-browserify-boilerplate/tree/lrl-154) and it doesn't work even with the webpack non-LiveReactload approach.

[They have a PR to fix this.](https://github.com/gaearon/react-hot-loader/pull/464)

The advantage of the new 4.x LiveReactload is that you will get these fixes from `react-hot-loader` rather than from us.

**Comment by ThisIsRuddy** [comment]
Just got merged 😊
